language: node_js
sudo: true

node_js:
  - "10.3.0"

services:
  - docker

# Use npm to install any local dependencies. This needs to install the dev
# dependencies as well because the 'npm run build' step uses them for some
# tranpiling.
#
# See here for why 'ci' is used instead of 'install':
# https://docs.npmjs.com/cli/ci
install:
  - npm ci

# Run the test suite and then the build step to perform any tranpiling
# steps to output final code.
script:
  - npm test
  - npm run build

# Assemble a docker image and publish it to dockerhub. This step requires
# the DOCKER_USER and DOCKER_PASS environment variables to be set. These
# are provided to travis in an encrypted form as secrets.
#
# The kubernetes cluster is configured to automatically pull the latest
# version out of the dockerhub repo.
after_success:
  - make image
  - make login
  - make push

